name: Health Check

on:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://fullstackopen-part11-deploy.herokuapp.com
          retry-delay: 5s